# Generated by Django 2.1.5 on 2019-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60, unique=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
